### ISSUE TITLE
validate(payload: any) in Implementing Passport JWT doc it's not correct

### ISSUE THREAD

**Issue by enricodevita** [nestjs/passport#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

in doc when you explain the validate method in [Implementing Passport JWT](https://docs.nestjs.com/security/authentication#implementing-passport-jwt) you wrote that pass payload and then use it's properties payload.sub and payload.username but in validate the parameter it's all Request Object so you have to extract token from parameter, decode it, then you have payload and you can use it.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt

### Expected behavior

I expect that payload in validate method it's the payload object and not entire Request

### Package version

9.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
The first parameter of the `validate` method should only be the `request` object if you have `passReqToCallback: true` set in the `super` options of the strategy. The sample you linked does indeed properly log out the `payload` as it does **not** set `passReqToCallback`. 

If you are still seeing a problem, please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

Otherwise for further assistance, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by enricodevita** [comment]
Thanks
now it's ok.
Excuse if i thought it was a bug.
