### ISSUE TITLE
WWW-Authenticate response header is missing

### ISSUE THREAD

**Issue by gtokarz** [nestjs/passport#279]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When passport-http-strategy is used, nest does not set WWW-Authenticate header https://tools.ietf.org/html/rfc6750, passport strategy currently prepares correct challenge, AuthGuard exposes it on req.authInfo, only thing missing is proper WWW-Authenticate header.

## Expected behavior
Response WWW-Authenticate header should be set according to challenge produced by passport

## Minimal reproduction of the problem with instructions
1. Any route with AuthGuard('bearer'), with strategy using passport-http-bearer
2. Send request without Authorization header
3. WWW-Authenticate header is to present on response

## What is the motivation / use case for changing the behavior?
https://tools.ietf.org/html/rfc6750

## Environment

<pre><code>
nestjs/passport version: 7.0.0
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  Windows

</code></pre>

**Comment by jmcdo29** [comment]
Does passport normally do this with express? `@nestjs/passport` is only a wrapper around passport with funcitonality to make it work in a nest-like fashion. If this doesn't happen automatically by passport, then `@nestjs/passport` won't do it either

**Comment by lkavicky** [comment]
Passport does automatically set the WWW-Authenticate header when all strategies failed  **if** you provide  no `callback` to the `authenticate` method (implementation [here](https://github.com/jaredhanson/passport/blob/b220766870cdbb98cc7570764cd3ced93da8945e/lib/middleware/authenticate.js#L104))
nestjs/passport always provides the callback:
https://github.com/nestjs/passport/blob/1034455518ab396958906dfc815c4c0badc1d737/lib/auth.guard.ts#L102
So that functionality is not accessible when using nestjs/passport.
You get the challenges passport uses to generate the WWW-Authenticate header in callback's 3rd parameter (`info`), but nestjs/passport is not doing anything with that param:
https://github.com/nestjs/passport/blob/1034455518ab396958906dfc815c4c0badc1d737/lib/auth.guard.ts#L79-L84

**Comment by stormsilver** [comment]
I just ran into this today while trying to implement auto-confirmation for AWS SNS topic subscriptions. SNS won't send the Authorization header unless the server responds with the WWW-Authenticate header in a 401 response to an initial request.

Given that passport does indeed do this, but nestjs/passport does not, I agree that this should be reopened.

@Jtalk if you're able, could you post your AuthGuard+pathes as a workaround until this gets fixed in the package?

**Comment by micalevisk** [comment]
@stormsilver I'd say that you should open a new issue requesting this as a feature request along with a potential API to this.
