### ISSUE TITLE
Throw a meaningful error when a Passport strategy is request-scoped

### ISSUE THREAD

**Issue by jessepinho** [nestjs/passport#320]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When a request-scoped dependency is injected into a Passport strategy, thus making the strategy itself request-scoped, Nest [can not initialize it](https://docs.nestjs.com/techniques/authentication#request-scoped-strategies). But there is no immediate error; instead, when attempting to hit an endpoint that uses the strategy, I see an error like "Unknown strategy 'local'."

## Expected behavior

Instead, it'd be nice to have a meaningful error message, like: "You have attempted to inject a Passport strategy that is request scoped. This can't be done; instead, please make sure your strategy and all of its dependencies are singleton-scoped."

(Not sure if this is possible, though — can an injected class know what scope is what injected with?)

## What is the motivation / use case for changing the behavior?

Passport strategies [can not be request-scoped](https://docs.nestjs.com/techniques/authentication#request-scoped-strategies). This means that all of its dependencies, and _their_ dependencies (and so on), must also not be request-scoped. However, it is easy to overlook when a request-scoped dependency has been added to a nested dependency of a strategy, and it's hard to test for this to ensure it doesn't happen.

It would make a lot of developers' lives easier to simply see a meaningful error as soon as they (intentionally or otherwise) try to make a Passport strategy request-scoped.

## Environment

<pre><code>
Nest version: @nestjs/passport `6.2.0`

 
For Tooling issues:
- Node version: v10.15.3  
- Platform: Mac OS Catalina 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Unfortunately, although I fully agree that the current exception is very ambiguous, there's no simple way we could throw a more meaningful error. The way this integration is designed is somewhat limited (due to architectural inconsistencies between Nest and Passport). In fact, each strategy is registered WHEN a strategy class is instantiated (within the constructor). However, request-scoped providers **are not instantiated** during the application bootstrap process (which is obvious). Hence, passport doesn't even know they exist and so "Unknown strategy" error :( Even if we add an additional check (condition) to the constructor, it will never be evaluated (since it's scoped to requests).

**Comment by jessepinho** [comment]
Gotcha — that's too bad. Thanks for explaining!
